// This file is automatically generated. Do not edit it directly.
import { createClient, type SupabaseClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = import.meta.env.VITE_SUPABASE_URL;
const SUPABASE_PUBLISHABLE_KEY = import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY;
const isSupabaseConfigured = Boolean(SUPABASE_URL && SUPABASE_PUBLISHABLE_KEY);

const createFallbackSupabaseClient = () => {
  const success = Promise.resolve({ data: null, error: null });
  const noConfigError = new Error("Supabase is not configured. Add VITE_SUPABASE_URL and VITE_SUPABASE_PUBLISHABLE_KEY to enable auth and persistence.");

  const query = {
    select: () => query,
    eq: () => query,
    single: async () => ({ data: null, error: null }),
    insert: async () => ({ data: null, error: null }),
    upsert: async () => ({ data: null, error: null }),
  };

  return {
    auth: {
      getSession: async () => ({ data: { session: null }, error: null }),
      onAuthStateChange: () => ({ data: { subscription: { unsubscribe: () => {} } }, error: null }),
      signOut: async () => ({ data: null, error: null }),
      signInWithPassword: async () => ({ data: { session: null, user: null }, error: noConfigError }),
      signInWithOAuth: async () => ({ data: null, error: noConfigError }),
      signUp: async () => ({ data: { session: null, user: null }, error: noConfigError }),
      resend: async () => ({ data: null, error: noConfigError }),
      verifyOtp: async () => ({ data: null, error: noConfigError }),
    },
    functions: {
      invoke: async () => ({ data: null, error: noConfigError }),
    },
    rpc: async (fnName: string) => {
      if (fnName === "get_current_month_usage") {
        return { data: 0, error: null };
      }

      return { data: null, error: null };
    },
    from: () => query,
  } as unknown as SupabaseClient<Database>;
};

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = isSupabaseConfigured
  ? createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
      auth: {
        storage: localStorage,
        persistSession: true,
        autoRefreshToken: true,
      },
    })
  : createFallbackSupabaseClient();
